### ISSUE TITLE
Format of ACL file

### ISSUE THREAD

**Issue by CodeMonkeyKevin** [prateeknischal/webtail#1]
What is the format of ACL file?

Something like this?
> username:password

**Comment by prateeknischal** [comment]
@CodeMonkeyKevin 
the ACL file only contains the username and **not** the password. The use case would be, if you have a machine with a generic authentication to it and not controlled by groups, say LDAP groups, then you might want to restrict the access.

So, just enter the usernames in the ACL file, only the usernames, and then only those users would be allowed even try to authenticate with the PAM.
